version: '3'

services:
  server:
    container_name: skeleton_nestjs
    links:
      - db

  db:
    image: postgres
    container_name: skeleton_db
    logging:
      driver: none
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./scripts/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:latest
    container_name: skeleton_minio
    volumes:
      - minio-data:/data
    logging:
      driver: none
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: minio server --console-address ":9001" /data

volumes:
  pg-data: {}
  minio-data: {}

