version: '3'

services:
  server:
    image: node:16
    working_dir: /usr/src/app
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
    networks:
      - skeleton
      - default
    ports:
      - "3000:3000"

  adminer:
    image: adminer
    container_name: skeleton_adminer
    logging:
      driver: none
    ports:
      - "8080:8080"

  db:
    environment:
      POSTGRES_MULTIPLE_DATABASES: skeleton,skeleton_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

networks:
  skeleton:
    external: true
